set(CMAKE_SYSTEM_NAME Linux) 
set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)

set(CMAKE_C_FLAGS "-m32" CACHE STRING "")
set(CMAKE_CXX_FLAGS "-m32" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS "-m32" CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS "-m32" CACHE STRING "")
