set(CMAKE_SYSTEM_NAME Windows) 
set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)

set(CMAKE_C_FLAGS "-m64" CACHE STRING "")
set(CMAKE_CXX_FLAGS "-m64" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS "-m64" CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS "-m64" CACHE STRING "")
